version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    network_mode: "host"
    restart: always

  rosblox-studio:
    image: ghcr.io/rosblox/studio:latest
    volumes:
      - ./studio/layout.json:/src/layout.json
    ports:
      - 8080:8080
    restart: always

  ros-rosbridge-suite:
    image: ghcr.io/rosblox/ros-rosbridge-suite:humble
    network_mode: "host"
    ipc: host
    pid: host
    environment:
      - UID=1000
      - GID=1000
    restart: always
    command: "su - ros /run.sh"
    
  ros-ros2-persist-parameter-server:
    image: ghcr.io/rosblox/ros-ros2-persist-parameter-server:humble
    restart: always
    volumes:
      - ./config/parameter_server.yaml:/tmp/parameter_server.yaml
    network_mode: "host"
    ipc: host
    pid: host
    environment: 
      - UID=1000
      - GID=1000
    command: "su - ros /run.sh"
